language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod

deploy:
  provider: s3
  access_key_id: "AKIAIV3Y2D2LMDTEXEFQ"
  secret_access_key: "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"
  region: "us-east-2"
  bucket: "gracebeck.co"
  skip_cleanup: true
  local_dir: dist/grace-beck-site
