language: node_js
node_js:
  - "10.9"
dist: trusty
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build

deploy:
  provider: pages
  local_dir: dist/gracekbeck
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
