language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod

deploy:
  provider: s3
  access_key_id: "AKIAIPDSYPYQTHD5MR7Q"
  secret_access_key: "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"
  region: "us-east-2"
  bucket: "gracebeck.co"
  skip_cleanup: true
  local_dir: dist/grace-beck-website
